version: '2'

services:
  elasticsearch:
    image: "docker-registry.nimaws.com/devops/monitoring/elasticsearch:5"
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - logging

  logstash:
    image: "docker-registry.nimaws.com/devops/monitoring/logstash:5"
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./logstash/config:/etc/logstash/conf.d"
    ports:
      - "5000:5000"
    networks:
      - logging

  kibana:
    image: "docker-registry.nimaws.com/devops/monitoring/kibana:5"
    build: kibana/
    volumes:
      - "./kibana/config/:/opt/kibana/config/"
    ports:
      - "5601:5601"
    networks:
      - logging

networks:
  logging:
    external: true 
